Add runtime error for pgindent if objdump is not installed

diff --git a/scripts/generate_typedefs.sh.in b/scripts/generate_typedefs.sh.in
--- a/scripts/generate_typedefs.sh.in
+++ b/scripts/generate_typedefs.sh.in
@@ -1,16 +1,21 @@
 #!/bin/bash
 
+if [ ! -x "@OBJDUMP@" ];
+then
+  echo "Cannot generate typedefs.list for pgindent because objdump is not installed" >&2
+  exit 1
+fi
 TMPDIR=${TMPDIR:-$(mktemp -d 2>/dev/null || mktemp -d -t 'timescaledb_typedef')}
 
 trap cleanup EXIT
 
 cleanup() {
-    rm -rf ${TMPDIR}
+  rm -rf ${TMPDIR}
 }
 
 @OBJDUMP@ -W @CMAKE_BINARY_DIR@/src/CMakeFiles/timescaledb.dir/*.o |egrep -A3 DW_TAG_typedef |perl -e 'while (<>) { chomp; @flds = split;next unless (1 < @flds);\
-     next if $flds[0]  ne "DW_AT_name" && $flds[1] ne "DW_AT_name";\
-     next if $flds[-1] =~ /^DW_FORM_str/;\
-     print $flds[-1],"\n"; }' |sort |uniq > ${TMPDIR}/typedefs.list.local
+   next if $flds[0]  ne "DW_AT_name" && $flds[1] ne "DW_AT_name";\
+   next if $flds[-1] =~ /^DW_FORM_str/;\
+   print $flds[-1],"\n"; }' |sort |uniq > ${TMPDIR}/typedefs.list.local
 wget -q -O - "http://www.pgbuildfarm.org/cgi-bin/typedefs.pl?branch=HEAD" |\
- cat - ${TMPDIR}/typedefs.list.local | sort | uniq
+  cat - ${TMPDIR}/typedefs.list.local | sort | uniq
