resolve conflicts

diff --git a/.github/workflows/release_post_release_ceremony.yaml b/.github/workflows/release_post_release_ceremony.yaml
--- a/.github/workflows/release_post_release_ceremony.yaml
+++ b/.github/workflows/release_post_release_ceremony.yaml
@@ -9,8 +9,21 @@ permissions:
   pull-requests: write
 
 jobs:
-  post-release-ceremony:
-    name: Post Release Ceremony
+  docs:
+    name: Post Release Ceremony - Documentation
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Generate list of GUCs
+        run: |
+          if gh workflow run tsdb-refresh-gucs-list.yaml -R timescale/docs -f tag=${{ github.event.release.tag_name }}; then
+            echo "✅ Triggered generation of GUC list in docs" >> $GITHUB_STEP_SUMMARY
+          else
+            echo "❌ docs workflow to generate the GUCs failed" >> $GITHUB_STEP_SUMMARY
+          fi
+
+  main-branch:
+    name: Post Release Ceremony - main branch
     runs-on: ubuntu-latest
 
     steps:
@@ -21,30 +34,68 @@ jobs:
         run: |
           ./scripts/release/build_post_release_artefacts.sh ${{ github.event.release.tag_name }}
 
-      - name: Create Pull Request for forward ported artefacts
-        id: cpr_fwdp
-        uses: peter-evans/create-pull-request@v7
+          BRANCH="release/${{ github.event.release.tag_name }}-main"
+          git checkout -b $BRANCH
+          git add version.config sql/updates/*.sql sql/CMakeLists.txt .unreleased/* CHANGELOG.md
+          git commit -m "forward port release artefacts of ${{ github.event.release.tag_name }} to main"
+          git push origin $BRANCH
+
+          BODY="- CHANGELOG\n- set previous_version in version.config\n- adjust CMakeList.txt with up & down grade files\n- removed .unreleased files"
+
+          PR_URL=$(gh pr create \
+            --title "Forwardport ${{ github.event.release.tag_name }}" \
+            --body "$BODY" \
+            --base main \
+            --head $BRANCH \
+            --delete-branch \
+            --label "release")
+          echo "# ✅ Forward ported release artefacts: $PR_URL" >> $GITHUB_STEP_SUMMARY
+
+  release-branch:
+    name: Post Release Ceremony - release branch
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout TimescaleDB
+        uses: actions/checkout@v4
         with:
-          token: ${{ secrets.ORG_AUTOMATION_TOKEN }}
-          branch: "release/${{ github.event.release.tag_name }}--forwardport"
-          base: "main"
-          delete-branch: true
-          title: "Forwardport ${{ github.event.release.tag_name }}"
-          body: |
-              - CHANGELOG
-              - set previous_version in version.config
-              - adjust CMakeList.txt with up & down grade files
-              - TODO removed .unreleased files
-          labels: |
-            release
-          add-paths: |
-            .unreleased/*
-            CHANGELOG.md
-            version.config
-            sql/updates/*.sql
-            sql/CMakeLists.txt
-      
-      - name: "Validate next version PR"
-        if: ${{ steps.cpr_fwdp.outputs.pull-request-number }}
+          ref: ${{ github.event.release.tag_name }}
+
+      - name: Bump to next version on release branch
         run: |
-          echo "Pull Request: ${{ steps.cpr_fwdp.outputs.pull-request-url }}"
+          TAGGED_VERSION=$(head -1 version.config | cut -d ' ' -f 3 | cut -d '-' -f 1)
+          if [[ "$TAGGED_VERSION" != "$${{ github.event.release.tag_name }}" ]]; then
+            echo "The tag: ${{ github.event.release.tag_name }} and the release version ${TAGGED_VERSION} do not match." >&2
+            echo "❌ tagged version ${{ github.event.release.tag_name }} is not matching the current version $TAGGED_VERSION" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+
+          RELEASE_BRANCH="${TAGGED_VERSION/%.d/.x}"
+          NEXT_VERSION=$(echo "$TAGGED_VERSION" | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
+          
+          echo "tagged version: ${TAGGED_VERSION}"
+          echo "next version: ${NEXT_VERSION}"
+
+          # adjust version.config file
+          sed -i \
+            -e "s/^version = .*/version = $NEXT_VERSION/" \
+            -e "s/^previous_version = .*/previous_version = $TAGGED_VERSION/" \
+            version.config
+
+          echo "# ✅ setting next patch version $TAGGED_VERSION in version.config" >> $GITHUB_STEP_SUMMARY
+          cat version.config >> $GITHUB_STEP_SUMMARY
+
+          BRANCH="release/bump-${{ github.event.release.tag_name }}-to-$NEXT_VERSION"
+          git checkout -b $BRANCH
+          git add version.config
+          git commit -m "Bump to next patch version $NEXT_VERSION"
+          git push origin $BRANCH
+
+          PR_URL=$(gh pr create \
+            --title "Forwardport ${{ github.event.release.tag_name }}" \
+            --body "Change to the next patch version $NEXT_VERSION after the release of ${{ github.event.release.tag_name }}." \
+            --base $RELEASE_BRANCH \
+            --head $BRANCH \
+            --delete-branch \
+            --label "release")
+          echo "# ✅ Bump to next patch version: $PR_URL" >> $GITHUB_STEP_SUMMARY
