Vectorize uuid eq, ne and bulk decomp UUIDs
Add vectorisation for UUID Eq and Ne filters and
support bulk decompression for UUIDs for:

- the new UUID compression
- dictionary compression
- array compression

The vectorisation brings about 2x improvements for
the UUID filters, plus it allows combining vectorised
UUID filters with other vectorised filter clauses.

diff --git a/.github/workflows/windows-build-and-test.yaml b/.github/workflows/windows-build-and-test.yaml
--- a/.github/workflows/windows-build-and-test.yaml
+++ b/.github/workflows/windows-build-and-test.yaml
@@ -90,7 +90,7 @@ jobs:
         vector_agg_groupagg
         vector_agg_grouping
         vector_agg_text
-        vector_agg_uuid_segmentby
+        vector_agg_uuid
         vectorized_aggregation
     steps:
     - name: Setup WSL
@@ -105,10 +105,13 @@ jobs:
         echo 'Acquire::http::Timeout "240";' >> /etc/apt/apt.conf.d/99retries
         echo 'Acquire::https::Timeout "240";' >> /etc/apt/apt.conf.d/99retries
 
+    # The apt-update is allowed to fail because of a known issue in WSL
+    # where the apt spec for the debian backports repo is messed up
+    # https://github.com/Vampire/setup-wsl/issues/76
     - name: Install additional packages in WSL
       shell: wsl-bash {0}
       run: |
-        apt-get update
+        apt-get update || true
         apt-get install --yes --no-install-recommends cmake gawk gcc git gnupg jq make postgresql-client postgresql-common tree
 
     - name: Configure git
